language: node_js
node_js:
  - '10.15.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn run lint
  - yarn run ci

