const EDIT_LOCATION = 'EDIT_LOCATION';

const FIELD_FIRST_NAME = 'FIELD_FIRST_NAME';
const FIELD_LAST_NAME = 'FIELD_LAST_NAME';
const FIELD_ADDRESS = 'FIELD_ADDRESS';
const FIELD_APT = 'FIELD_APT';
const FIELD_CITY = 'FIELD_CITY';
const FIELD_ZIP_CODE = 'FIELD_ZIP_CODE';
const FIELD_PHONE_NUMBER = 'FIELD_PHONE_NUMBER';
const FIELD_COUNTRY = 'FIELD_COUNTRY';
const FIELD_STATE = 'FIELD_STATE';
